spring.datasource.url=jdbc:h2:mem:usertaskdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.settings.application-title=User Task API (Dev)
app.settings.pagination-limit=10
app.settings.contact-email=dev@example.com

logging.level.com.tamar.user_task_api=DEBUG
logging.level.root=INFO
