spring.application.name=user-task-api
server.port=8081
spring.profiles.active=dev

spring.messages.encoding=UTF-8
spring.messages.basename=messages

logging.file.name=logs/app.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.access=unrestricted
management.endpoint.health.show-details=when-authorized
management.endpoint.health.roles=ADMIN
management.endpoint.info.access=unrestricted
management.endpoint.metrics.access=unrestricted
info.app.name=${spring.application.name}
info.app.description=User and task management REST API
