spring.application.name=user-task-api
server.port=8081
spring.profiles.active=dev

spring.messages.encoding=UTF-8
spring.messages.basename=messages

logging.file.name=logs/app.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7
