spring.datasource.url=jdbc:postgresql://localhost:5432/usertaskdb
spring.datasource.username=postgres
spring.datasource.password=changeme
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=false

app.settings.application-title=User Task API
app.settings.pagination-limit=50
app.settings.contact-email=support@example.com

#quieter logging (WARN/ERROR)
logging.level.com.tamar.user_task_api=WARN
logging.level.root=ERROR
